# Generated by Django 4.1.4 on 2023-01-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
