# Generated by Django 4.1.4 on 2023-01-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Description')),
                ('resolution', models.TextField(default='', max_length=500, verbose_name='Resolution')),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('UI', 'User-Interface'), ('FEATURE', 'Feature')], default='BUG', max_length=11, verbose_name='Type')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=11, verbose_name='Status')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], default='NORMAL', max_length=8, verbose_name='Priority')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assignees')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Description')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('title', models.CharField(default='', max_length=20, verbose_name='Title')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ticket', verbose_name='Ticket')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name': 'Ticket comment',
                'verbose_name_plural': 'Ticket comments',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.tracker', verbose_name='Tracker'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updater', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
